# OSS Appender YAML Configuration Example

# AWS S3 Configuration
aws:
  s3:
    endpoint: https://s3.amazonaws.com
    region: us-east-1
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    bucket: my-log-bucket
    pathStyleAccess: false
    connectTimeout: 30000
    readTimeout: 60000
    maxConnections: 50
    enableSsl: true

# MinIO Configuration
minio:
  endpoint: http://localhost:9000
  region: us-east-1
  accessKeyId: minioadmin
  secretAccessKey: minioadmin
  bucket: logs
  pathStyleAccess: true
  connectTimeout: 30000
  readTimeout: 60000
  maxConnections: 50
  enableSsl: false

# Generic S3 Configuration
s3:
  endpoint: https://your-s3-compatible-service.com
  region: us-east-1
  accessKeyId: ${S3_ACCESS_KEY}
  secretAccessKey: ${S3_SECRET_KEY}
  bucket: application-logs
  pathStyleAccess: false
  connectTimeout: 30000
  readTimeout: 60000
  maxConnections: 50
  enableSsl: true

# Batch Processing Configuration
batch:
  size: 100
  maxMessageAgeMs: 600000
  maxBytes: 1048576

# Queue Configuration
queue:
  capacity: 8192
  blockWhenFull: false

# Thread Pool Configuration
thread:
  poolSize: 2
  maxPoolSize: 4
  keepAliveTime: 60000

# Retry Configuration
retry:
  maxAttempts: 3
  baseDelayMs: 1000
  maxDelayMs: 30000

# Spring Boot Integration Example
spring:
  application:
    name: my-app
  profiles:
    active: production

# Logging Configuration
logging:
  config: classpath:logback-spring.xml
  level:
    org.logx: INFO
    root: WARN