# Logback OSS Appender Spring Boot 配置示例

logging:
  logback:
    oss:
      # 启用OSS Appender
      enabled: true

      # S3兼容存储配置（必需）
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      region: cn-hangzhou
      access-key-id: ${OSS_ACCESS_KEY_ID:your-access-key}
      access-key-secret: ${OSS_ACCESS_KEY_SECRET:your-secret-key}
      bucket: my-logs-bucket

      # 可选配置
      key-prefix: spring-boot-logs/
      pattern: "%d{ISO8601} [%t] %-5level %logger{36} [%X{traceId}] - %msg%n"
      level: INFO

      # 性能调优配置
      max-queue-size: 200000
      max-batch-count: 5000
      max-batch-bytes: 4194304
      flush-interval-ms: 2000
      drop-when-queue-full: false
      multi-producer: false

      # 重试配置
      max-retries: 5
      base-backoff-ms: 200
      max-backoff-ms: 10000

# Spring Boot Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,logback-oss
  endpoint:
    health:
      show-details: always
  health:
    logback-oss:
      enabled: true

# 其他存储后端配置示例：

# AWS S3
#logging:
#  logback:
#    oss:
#      enabled: true
#      endpoint: https://s3.amazonaws.com
#      region: us-east-1
#      access-key-id: ${AWS_ACCESS_KEY_ID}
#      access-key-secret: ${AWS_SECRET_ACCESS_KEY}
#      bucket: my-aws-logs-bucket

# MinIO
#logging:
#  logback:
#    oss:
#      enabled: true
#      endpoint: http://localhost:9000
#      region: us-east-1
#      access-key-id: minioadmin
#      access-key-secret: minioadmin
#      bucket: logs

# 腾讯云COS
#logging:
#  logback:
#    oss:
#      enabled: true
#      endpoint: https://cos.ap-beijing.myqcloud.com
#      region: ap-beijing
#      access-key-id: ${COS_SECRET_ID}
#      access-key-secret: ${COS_SECRET_KEY}
#      bucket: my-cos-logs-bucket